# Generated by Django 5.1.4 on 2025-01-18 19:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subscribers', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subscribers',
            options={'ordering': ['-subscribed_at'], 'verbose_name': 'Subscribers', 'verbose_name_plural': 'Subscribers'},
        ),
    ]
