# Generated by Django 5.1.4 on 2025-01-12 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_blogchangelog'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='bio',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='author',
            name='linkedin_handle',
            field=models.URLField(blank=True, null=True),
        ),
    ]
